definitions:
  service.GenericErrResp:
    properties:
      error_msg:
        type: string
    type: object
  service.GetMenuRespV1:
    properties:
      menu:
        $ref: '#/definitions/service.MenuRespV1'
    type: object
  service.MenuRespV1:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
info:
  contact: {}
  description: This is a cookbook menu app.
  title: cookbook menu app
  version: "1.0"
paths:
  /menu:
    get:
      consumes:
      - application/json
      description: get menu
      operationId: GetMenuV1
      parameters:
      - in: query
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.GetMenuRespV1'
        default:
          description: ""
          schema:
            $ref: '#/definitions/service.GenericErrResp'
      summary: get menu
      tags:
      - menu
    post:
      consumes:
      - application/json
      description: save menu
      operationId: SaveMenuV1
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.GenericErrResp'
        default:
          description: ""
          schema:
            $ref: '#/definitions/service.GenericErrResp'
      summary: save menu
      tags:
      - menu
swagger: "2.0"
