// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1
// source: cookbook.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMenusInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetMenusInput) Reset() {
	*x = GetMenusInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cookbook_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMenusInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenusInput) ProtoMessage() {}

func (x *GetMenusInput) ProtoReflect() protoreflect.Message {
	mi := &file_cookbook_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenusInput.ProtoReflect.Descriptor instead.
func (*GetMenusInput) Descriptor() ([]byte, []int) {
	return file_cookbook_proto_rawDescGZIP(), []int{0}
}

type GetMenusOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Menus []*MenuInfo `protobuf:"bytes,1,rep,name=menus,proto3" json:"menus,omitempty"`
}

func (x *GetMenusOutput) Reset() {
	*x = GetMenusOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cookbook_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMenusOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenusOutput) ProtoMessage() {}

func (x *GetMenusOutput) ProtoReflect() protoreflect.Message {
	mi := &file_cookbook_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenusOutput.ProtoReflect.Descriptor instead.
func (*GetMenusOutput) Descriptor() ([]byte, []int) {
	return file_cookbook_proto_rawDescGZIP(), []int{1}
}

func (x *GetMenusOutput) GetMenus() []*MenuInfo {
	if x != nil {
		return x.Menus
	}
	return nil
}

type MenuInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MenuId   int64  `protobuf:"varint,1,opt,name=menuId,proto3" json:"menuId,omitempty"`
	MenuName string `protobuf:"bytes,2,opt,name=menuName,proto3" json:"menuName,omitempty"`
}

func (x *MenuInfo) Reset() {
	*x = MenuInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cookbook_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MenuInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuInfo) ProtoMessage() {}

func (x *MenuInfo) ProtoReflect() protoreflect.Message {
	mi := &file_cookbook_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuInfo.ProtoReflect.Descriptor instead.
func (*MenuInfo) Descriptor() ([]byte, []int) {
	return file_cookbook_proto_rawDescGZIP(), []int{2}
}

func (x *MenuInfo) GetMenuId() int64 {
	if x != nil {
		return x.MenuId
	}
	return 0
}

func (x *MenuInfo) GetMenuName() string {
	if x != nil {
		return x.MenuName
	}
	return ""
}

var File_cookbook_proto protoreflect.FileDescriptor

var file_cookbook_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x63, 0x6f, 0x6f, 0x6b, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x0f, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6e, 0x75, 0x73, 0x49, 0x6e, 0x70, 0x75,
	0x74, 0x22, 0x31, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6e, 0x75, 0x73, 0x4f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x12, 0x1f, 0x0a, 0x05, 0x6d, 0x65, 0x6e, 0x75, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x09, 0x2e, 0x4d, 0x65, 0x6e, 0x75, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x6d,
	0x65, 0x6e, 0x75, 0x73, 0x22, 0x3e, 0x0a, 0x08, 0x4d, 0x65, 0x6e, 0x75, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6e, 0x75, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x6d, 0x65, 0x6e, 0x75, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65, 0x6e, 0x75,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x65, 0x6e, 0x75,
	0x4e, 0x61, 0x6d, 0x65, 0x32, 0x35, 0x0a, 0x04, 0x4d, 0x65, 0x6e, 0x75, 0x12, 0x2d, 0x0a, 0x08,
	0x47, 0x65, 0x74, 0x4d, 0x65, 0x6e, 0x75, 0x73, 0x12, 0x0e, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65,
	0x6e, 0x75, 0x73, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x0f, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65,
	0x6e, 0x75, 0x73, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x00, 0x42, 0x1d, 0x5a, 0x1b, 0x6c,
	0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f,
	0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_cookbook_proto_rawDescOnce sync.Once
	file_cookbook_proto_rawDescData = file_cookbook_proto_rawDesc
)

func file_cookbook_proto_rawDescGZIP() []byte {
	file_cookbook_proto_rawDescOnce.Do(func() {
		file_cookbook_proto_rawDescData = protoimpl.X.CompressGZIP(file_cookbook_proto_rawDescData)
	})
	return file_cookbook_proto_rawDescData
}

var file_cookbook_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cookbook_proto_goTypes = []interface{}{
	(*GetMenusInput)(nil),  // 0: GetMenusInput
	(*GetMenusOutput)(nil), // 1: GetMenusOutput
	(*MenuInfo)(nil),       // 2: MenuInfo
}
var file_cookbook_proto_depIdxs = []int32{
	2, // 0: GetMenusOutput.menus:type_name -> MenuInfo
	0, // 1: Menu.GetMenus:input_type -> GetMenusInput
	1, // 2: Menu.GetMenus:output_type -> GetMenusOutput
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cookbook_proto_init() }
func file_cookbook_proto_init() {
	if File_cookbook_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cookbook_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMenusInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cookbook_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMenusOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cookbook_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MenuInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cookbook_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cookbook_proto_goTypes,
		DependencyIndexes: file_cookbook_proto_depIdxs,
		MessageInfos:      file_cookbook_proto_msgTypes,
	}.Build()
	File_cookbook_proto = out.File
	file_cookbook_proto_rawDesc = nil
	file_cookbook_proto_goTypes = nil
	file_cookbook_proto_depIdxs = nil
}
