// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"learning/project_demo/internal/biz"
	"learning/project_demo/internal/data"
	"learning/project_demo/internal/service"
	"learning/project_demo/internal/rpcservice"
)

// Injectors from wire.go:

// initCookbookApp init my cookbook application.
func initCookbookApp() *cookbookApp {
	menuRepo := data.NewMenuRepo()
	menuUsecase := biz.NewMenuUsecase(menuRepo)
	menuService := service.NewMenuService(menuUsecase)
	menuRpcService := rpcservice.NewMenuRpcService(menuUsecase)
	mainCookbookApp := newCookbookApp(menuService, menuRpcService)
	return mainCookbookApp
}
